### ISSUE TITLE
Error on logout 

### ISSUE THREAD

**Issue by elsiehoffet-94** [arkhn/warehouse-api#149] opened 2020-10-01 12:28 UTC
## Description
Logout on front-api will result in an invalid request error

## Reproduction

1. Connect to front-api
2. Logout
3. See error.

## Screenshots
```
 The OAuth2 request resulted in an error.

    Error: invalid_request
    Description: The request is missing a required parameter, includes an invalid parameter value, includes a parameter more than once, or is otherwise malformed
    Hint: Logout failed because query parameter post_logout_redirect_uri is not a whitelisted as a post_logout_redirect_uri for the client
    Debug:

You are seeing this page because configuration key urls.error is not set.

If you are an administrator, please read the guide to understand what you need to do. If you are a user, please contact the administrator. 
```

## Environment
Staging, rms

## Resolution
Maybe the config `urls.error ` is missing

**Comment by simonvadee** [comment] 2020-10-01 12:37
Duplicate of arkhn/identity-provider#21

**Closed by simonvadee** 2020-10-01 12:37 UTC
Labels: Low Priority
